### ISSUE TITLE
webpack dev server hangs on sequential tests

### ISSUE THREAD

**Issue by drptbl** [deshiknaves/cypress-msw-interceptor#1]
Hey,

First of all, thanks for this awesome project ;). Saves some time.

I'm having two issues:
1. I'm running my tests on local webpack dev server in a loop for each resolution provided in a test. First two are passing without issues with test code below, however third one timesout on `cy.visit()`. Like it makes webpack dev server to hang(?). I have no issues while running my tests without this plugin.
2. The request that I'm waiting for is `POST` to graphql API. But I'm not trying to mock anything just want to track it and wait for it and it seems to work properly for first two runs.
3. After looking at browser console in cypress, I'm able to see this error (maybe related?):
<img width="543" alt="Screenshot 2020-09-25 at 14 22 00" src="https://user-images.githubusercontent.com/8177587/94267160-64f2ab80-ff3b-11ea-8804-151c00d03be7.png">

Related test code:
```
describe('Test different resolutions', () => {
	context('desktop, mobile and tablet resolutions', () => {
		const allSizes = [...];
		allSizes.forEach((resolution) => {
			it(`Should display exchange properly on ${resolution} screen`, () => {
				cy.viewport(resolution[0], resolution[1]);
				cy.interceptRequest(
					'POST',
					'https://somexternalurl.com/api'
				).as('api');
				cy.visit('http://localhost:3000');
				cy.waitForRequest('@api');
				cy.screenshot(`${resolution[0]}-${resolution[1]}`);
			});
		});
	});
});
```

**Comment by deshiknaves** [comment]
The service worker is outdated because I still have a couple of PRs that need to get merged into MSW. I will keep you posted on that.

I haven't tested this a lot with GraphQL, I will over the next 2 days, it's on my roadmap. Let me have a look at this and I'll get back to you shortly.

**Comment by deshiknaves** [comment]
Oh yeah, it will not work because of the way that I'm tracking requests — they are currently using the the `REST` method to track them. This is not a big task, I just haven't gotten to it yet. I'll get back to you soon 😊

**Comment by drptbl** [comment]
@deshiknaves Thanks again 🙏. It looks very promising 🚀.

**Comment by deshiknaves** [comment]
Hey, I'm still working on GraphQL and it's API. However, I noticed that you're just mocking the REST method, which it can do already. I had a look at your example and replicated it on this branch: https://github.com/deshiknaves/cypress-msw-interceptor/blob/feature/resolutions-in-a-loop/cypress/integration/REST.spec.js

I'm not noticing it hanging at all. Maybe it's in conjunction with something else?

**Comment by drptbl** [comment]
@deshiknaves could be related to the fact that I'm running these tests on local webpack dev server (`http://localhost:3000`)? Maybe there is some conjunction there?
