### ISSUE TITLE
error "TypeError : cannot read 'type'

### ISSUE THREAD

**Issue by zjxjohnxtlxb** [deshiknaves/cypress-msw-interceptor#10]
This error occurs when cypress starts new test case and the last test case hasn't fully executed then async function **composeeRequest** yet.

I added 

> " if (type == undefined) return "

 in line:87 to solve the problem.

![Capture d’écran de 2021-11-29 19-14-10](https://user-images.githubusercontent.com/59448317/143923568-0ae7b357-0e56-4ec5-b144-ee51f24bfc4c.png)
[](url)
I think it's because cypress release immediately resources between each test.

**Comment by ryanfiller** [comment]
Props to @zjxjohnxtlxb because that appears to be the fix (for me, so far, at least). I'm using [`patch-package`](https://www.npmjs.com/package/patch-package) to work around this for now, [here](https://github.com/deshiknaves/cypress-msw-interceptor/pull/12) is a PR for a permanent fix.
