### ISSUE TITLE
Doesn't work with Next & TS

### ISSUE THREAD

**Issue by pitis** [deshiknaves/cypress-msw-interceptor#5]
"cypress": "8.6.0",
"cypress-msw-interceptor": "^2.0.0",
"msw": "^0.35.0",

Hey there, I'm trying to make this work with a project that has NextJS and TS support.

I already had msw set up, and I followed the docs for this package, but when I open cypress I get this:

Error: Webpack Compilation Error
./node_modules/cypress-msw-interceptor/src/support.js 41:14
Module parse failed: Unexpected token (41:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| function registerRequest(request) {
>   if (request?.body?.operationName) {
|     registerGraphQL(request)
|   }
 @ ./node_modules/cypress-msw-interceptor/index.js 4:0-27

**Comment by deshiknaves** [comment]
This has been resolved now
