### ISSUE TITLE
Service Worker script does not exist at the given path

### ISSUE THREAD

**Issue by mlaw93** [deshiknaves/cypress-msw-interceptor#7]
error on ` import 'cypress-msw-interceptor'`

says

`Failed to register a Service Worker for scope ('http://localhost:51138/') with script ('http://localhost:51138/mockServiceWorker.js'): Service Worker script does not exist at the given path.`

I haven't gotten to actually writing any special test scenario.  Just a simple test to cy.visit page.

**Comment by deshiknaves** [comment]
Have you installed `msw` to your application following this guide? https://mswjs.io/docs/getting-started/integrate/browser

**Comment by mlaw93** [comment]
Yes.  I have msw  installed and working for a while now. I am now adding cypress and was wanting to use this plugin to use it with msw but getting this error.

**Comment by mwarger** [comment]
I am seeing this issue as well @deshiknaves.

**Comment by deshiknaves** [comment]
@mwarger what port is your application hosted? I'm going to enable a way for you to specify where the service worker is. Will look at working on this this weekend.

**Comment by mwarger** [comment]
@deshiknaves The application is running on port 1962.

**Comment by mwarger** [comment]
@deshiknaves I found I could get around this by supplying a `baseUrl` in `cypress.json`.

**Comment by mlaw93** [comment]
Mine is port 8087

**Comment by deshiknaves** [comment]
I've updated the README.md. You will need to set the `baseUrl` so that Cypress can load the service worker from the same domain.
